In [1]:
#import libraries
import numpy as np
import pandas as pd

In [2]:
#import dataset
df=pd.read_csv('/content/uber_ncr_ride_bookings.csv')

In [3]:
#checking for data
df.head()

,Date,Time,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,...,Reason for cancelling by Customer,Cancelled Rides by Driver,Driver Cancellation Reason,Incomplete Rides,Incomplete Rides Reason,Booking Value,Ride Distance,Driver Ratings,Customer Rating,Payment Method
0,2024-03-23,12:29:38,"""CNR5884300""",No Driver Found,"""CID1982111""",eBike,Palam Vihar,Jhilmil,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024-11-29,18:01:39,"""CNR1326809""",Incomplete,"""CID4604802""",Go Sedan,Shastri Nagar,Gurgaon Sector 56,4.9,14.0,...,NaN,NaN,NaN,1.0,Vehicle Breakdown,237.0,5.73,NaN,NaN,UPI
2,2024-08-23,08:56:10,"""CNR8494506""",Completed,"""CID9202816""",Auto,Khandsa,Malviya Nagar,13.4,25.8,...,NaN,NaN,NaN,NaN,NaN,627.0,13.58,4.9,4.9,Debit Card
3,2024-10-21,17:17:25,"""CNR8906825""",Completed,"""CID2610914""",Premier Sedan,Central Secretariat,Inderlok,13.1,28.5,...,NaN,NaN,NaN,NaN,NaN,416.0,34.02,4.6,5.0,UPI
4,2024-09-16,22:08:00,"""CNR1950162""",Completed,"""CID9933542""",Bike,Ghitorni Village,Khan Market,5.3,19.6,...,NaN,NaN,NaN,NaN,NaN,737.0,48.21,4.1,4.3,UPI

In [12]:
#check null values in dataset
df.isnull().sum()

Date                                     0
Time                                     0
Booking ID                               0
Booking Status                           0
Customer ID                              0
Vehicle Type                             0
Pickup Location                          0
Drop Location                            0
Avg VTAT                                 0
Avg CTAT                                 0
Cancelled Rides by Customer              0
Reason for cancelling by Customer        0
Cancelled Rides by Driver                0
Driver Cancellation Reason               0
Incomplete Rides                         0
Incomplete Rides Reason                  0
Booking Value                            0
Ride Distance                            0
Driver Ratings                       35138
Customer Rating                      35138
Payment Method                       29551
dtype: int64

In [8]:
#checing data types of columns
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 92392 entries, 0 to 92391
Data columns (total 21 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Date                               92392 non-null  object
 1   Time                               92392 non-null  object
 2   Booking ID                         92392 non-null  object
 3   Booking Status                     92392 non-null  object
 4   Customer ID                        92392 non-null  object
 5   Vehicle Type                       92392 non-null  object
 6   Pickup Location                    92392 non-null  object
 7   Drop Location                      92392 non-null  object
 8   Avg VTAT                           85885 non-null  float64
 9   Avg CTAT                           62841 non-null  float64
 10  Cancelled Rides by Customer        6399 non-null   float64
 11  Reason for cancelling by Customer  6399 non-null   object
 12  Cancelled Rides by Driver          16645 non-null  float64
 13  Driver Cancellation Reason         16645 non-null  object
 14  Incomplete Rides                   5587 non-null   float64
 15  Incomplete Rides Reason            5587 non-null   object
 16  Booking Value                      62841 non-null  float64
 17  Ride Distance                      62841 non-null  float64
 18  Driver Ratings                     57254 non-null  float64
 19  Customer Rating                    57254 non-null  float64
 20  Payment Method                     62841 non-null  object
dtypes: float64(9), object(12)
memory usage: 14.8+ MB

In [9]:
#fill missing values
categorical_cols = ['Reason for cancelling by Customer', 'Driver Cancellation Reason', 'Incomplete Rides Reason']
for col in categorical_cols:
    df[col] = df[col].fillna('Unknown')

In [10]:
#fill missing values
numerical_cols = ['Avg VTAT', 'Avg CTAT', 'Booking Value', 'Ride Distance']
for col in numerical_cols:
    df[col] = df[col].fillna(df[col].median())

In [11]:
#fill 0  in missing values
status_cols = ['Cancelled Rides by Customer', 'Cancelled Rides by Driver', 'Incomplete Rides']
for col in status_cols:
    df[col] = df[col].fillna(0)

In [13]:
#fill 0  in missing values
rating_cols = ['Driver Ratings']
for col in rating_cols:
  df[col] = df[col].fillna(0)

In [14]:
#fill 0  in missing values
cus_rating_cols = ['Customer Rating']
for col in cus_rating_cols:
  df[col] = df[col].fillna(0)

In [15]:
#fill 'Unknown' in 'Payment Method' column
df['Payment Method'] = df['Payment Method'].fillna('Unknown')

In [16]:
#cheking null values after fill values
df.isnull().sum()

Date                                 0
Time                                 0
Booking ID                           0
Booking Status                       0
Customer ID                          0
Vehicle Type                         0
Pickup Location                      0
Drop Location                        0
Avg VTAT                             0
Avg CTAT                             0
Cancelled Rides by Customer          0
Reason for cancelling by Customer    0
Cancelled Rides by Driver            0
Driver Cancellation Reason           0
Incomplete Rides                     0
Incomplete Rides Reason              0
Booking Value                        0
Ride Distance                        0
Driver Ratings                       0
Customer Rating                      0
Payment Method                       0
dtype: int64

In [18]:
#checking for duplicate values
df.duplicated().sum()

np.int64(0)

In [19]:
#replace data type of columns in category from object
for col in df.select_dtypes(include=['object']).columns:
    df[col] = df[col].astype('category')

In [20]:
#checking for data type
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 92392 entries, 0 to 92391
Data columns (total 21 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Date                               92392 non-null  category
 1   Time                               92392 non-null  category
 2   Booking ID                         92392 non-null  category
 3   Booking Status                     92392 non-null  category
 4   Customer ID                        92392 non-null  category
 5   Vehicle Type                       92392 non-null  category
 6   Pickup Location                    92392 non-null  category
 7   Drop Location                      92392 non-null  category
 8   Avg VTAT                           92392 non-null  float64
 9   Avg CTAT                           92392 non-null  float64
 10  Cancelled Rides by Customer        92392 non-null  float64
 11  Reason for cancelling by Customer  92392 non-null  category
 12  Cancelled Rides by Driver          92392 non-null  float64
 13  Driver Cancellation Reason         92392 non-null  category
 14  Incomplete Rides                   92392 non-null  float64
 15  Incomplete Rides Reason            92392 non-null  category
 16  Booking Value                      92392 non-null  float64
 17  Ride Distance                      92392 non-null  float64
 18  Driver Ratings                     92392 non-null  float64
 19  Customer Rating                    92392 non-null  float64
 20  Payment Method                     92392 non-null  category
dtypes: category(12), float64(9)
memory usage: 16.3 MB

In [21]:
#replace all spaces in column names in underscore
df.columns = df.columns.str.replace(' ', '_')

In [23]:
#checking for column's names
df.columns

Index(['Date', 'Time', 'Booking_ID', 'Booking_Status', 'Customer_ID',
       'Vehicle_Type', 'Pickup_Location', 'Drop_Location', 'Avg_VTAT',
       'Avg_CTAT', 'Cancelled_Rides_by_Customer',
       'Reason_for_cancelling_by_Customer', 'Cancelled_Rides_by_Driver',
       'Driver_Cancellation_Reason', 'Incomplete_Rides',
       'Incomplete_Rides_Reason', 'Booking_Value', 'Ride_Distance',
       'Driver_Ratings', 'Customer_Rating', 'Payment_Method'],
      dtype='object')

In [25]:
#checking for nunique values
df.nunique()

Date                                   365
Time                                 51161
Booking_ID                           91931
Booking_Status                           5
Customer_ID                          91935
Vehicle_Type                             7
Pickup_Location                        176
Drop_Location                          176
Avg_VTAT                               181
Avg_CTAT                               351
Cancelled_Rides_by_Customer              2
Reason_for_cancelling_by_Customer        6
Cancelled_Rides_by_Driver                2
Driver_Cancellation_Reason               6
Incomplete_Rides                         2
Incomplete_Rides_Reason                  4
Booking_Value                         2286
Ride_Distance                         4894
Driver_Ratings                          22
Customer_Rating                         22
Payment_Method                           6
dtype: int64

In [26]:
#use statistics of data set
df.describe()

,Avg_VTAT,Avg_CTAT,Cancelled_Rides_by_Customer,Cancelled_Rides_by_Driver,Incomplete_Rides,Booking_Value,Ride_Distance,Driver_Ratings,Customer_Rating
count,92392.000000,92392.000000,92392.000000,92392.000000,92392.000000,92392.000000,92392.000000,92392.000000,92392.000000
mean,8.453755,28.998925,0.069259,0.180156,0.060471,478.336230,24.387258,2.622479,2.728474
std,3.645736,7.346286,0.253896,0.384320,0.238358,326.989674,11.551392,2.083078,2.165185
min,2.000000,10.000000,0.000000,0.000000,0.000000,50.000000,1.000000,0.000000,0.000000
25%,5.600000,24.900000,0.000000,0.000000,0.000000,321.000000,17.430000,0.000000,0.000000
50%,8.300000,28.700000,0.000000,0.000000,0.000000,415.000000,23.770000,3.900000,4.100000
75%,11.000000,32.900000,0.000000,0.000000,0.000000,522.000000,30.700000,4.300000,4.600000
max,20.000000,45.000000,1.000000,1.000000,1.000000,4277.000000,50.000000,5.000000,5.000000

In [27]:
#data is cleaned & save the data set with changes
df.to_csv('uber_cleaned.csv', index=False)

In [33]:
import matplotlib.pyplot as plt
import seaborn as sns
#Business & Booking Insights
#What is the overall booking success rate?
total_bookings = len(df)
total_bookings

92392

In [39]:
successful_bookings = len(df[df['Booking_Status'] == 'Completed'])
successful_bookings

57254

In [40]:
overall_success_rate = (successful_bookings / total_bookings) * 100
overall_success_rate

print(f"Total Bookings: {total_bookings}")
print(f"Successful Bookings: {successful_bookings}")
print(f"Overall Booking Success Rate: {overall_success_rate:.2f}%")

Total Bookings: 92392
Successful Bookings: 57254
Overall Booking Success Rate: 61.97%